name: Tox

on: [push, pull_request]

jobs:
  tox:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - 'pypy-3.7'
          - 'pypy-3.8'
          - 'pypy-3.9'

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade PyPA packages
        run: python -m pip install -U pip setuptools wheel

      - if: matrix.os == 'macos-latest'
        name: Update PATH (macOS)
        run: echo "$HOME/.local/bin" >>"$GITHUB_PATH"

      - if: matrix.os == 'windows-latest'
        name: Update PATH (Windows)
        run: echo "$APPDATA/Python/Scripts" >>"$GITHUB_PATH"

      # TODO: Print the install script commit hash and Poetry version.
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/EliahKagan/install.python-poetry.org/ci-repro/subaudit/install-poetry.py |
              python -

      - name: Install tox and tox-gh-actions
        run: python -m pip install -U 'tox==4.*' 'tox-gh-actions==3.*'

      - name: Check with tox
        run: tox
